version: "3"

services:
  openrave:
    image: ubuntu_gui:latest 
    # build: .
    privileged: true
    tty: true
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DISABLE_REQUIRE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
