version: '2'
services:
  jedai:
      image: jedai:testing
      environment:
        - DISPLAY=novnc:0.0
      depends_on:
        - novnc    
      # command: /root/git/AAIR-JEDAI/.start-jedai.sh
      
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=720
      - RUN_XTERM=no
    ports:
      - ${PORT}:8080 #host_port:container_port

# PORT=8081 && docker-compose -p service2  up -d
    # PORT is setting the env variable but need to have PORT as a variable in host machine's variables
    # -p <prefix> : sets the prefix for the docker services which allows to launch multiple instances of containers.
      # still need to change the <prefix> name for each instance somehow. but as planning to run this command as a response to 
      # a request to the webserver or something so this can actually be dynamically set using some logic.